/*
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT!
 *
 * generated by gattdbgen from sink_gatt_db.db_
 */
#ifndef __SINK_GATT_DB_H
#define __SINK_GATT_DB_H

#include <csrtypes.h>

#define HANDLE_GATT_SERVICE             (0x0001)
#define HANDLE_GATT_SERVICE_END         (0x0006)
#define HANDLE_GATT_SERVICE_CHANGED     (0x0003)
#define HANDLE_GATT_SERVICE_CHANGED_CLIENT_CONFIG (0x0004)
#define HANDLE_GATT_CLIENT_SUPPORTED_FEATURES (0x0006)
#define HANDLE_GAP_SERVICE              (0x0007)
#define HANDLE_GAP_SERVICE_END          (0x000b)
#define HANDLE_DEVICE_NAME              (0x0009)
#define HANDLE_DEVICE_APPEARANCE        (0x000b)
#define HANDLE_IMM_ALERT_SERVICE        (0x000c)
#define HANDLE_IMM_ALERT_SERVICE_END    (0x000e)
#define HANDLE_IMM_ALERT_LEVEL          (0x000e)
#define HANDLE_GAIA_SERVICE             (0x000f)
#define HANDLE_GAIA_SERVICE_END         (0xffff)
#define HANDLE_GAIA_COMMAND_ENDPOINT    (0x0011)
#define HANDLE_GAIA_RESPONSE_ENDPOINT   (0x0013)
#define HANDLE_GAIA_RESPONSE_CLIENT_CONFIG (0x0014)
#define HANDLE_GAIA_DATA_ENDPOINT       (0x0016)
#define HANDLE_GAIA_DATA_CLIENT_CONFIG  (0x0017)

typedef enum
{
    GAP_SERVICE,
    
    gatt_sdp_last
} gatt_sdp;

uint8 *GattGetServiceRecord(gatt_sdp service, uint16 *len);
uint16 *GattGetDatabase(uint16 *len);
uint16 GattGetDatabaseSize(void);

#endif

/* End-of-File */
